### ISSUE TITLE
Setting custom style on cloud throws an exception

### ISSUE THREAD

**Issue by alexresolute** [jasondavies/d3-cloud#186]
Hi, a previously supported feature, using `.style("fill", (d,i) => { return fill(i) })` seems to have been removed. Is there no support for custom colors now? It seems as though fill style is hard coded to red now?

**Comment by jasondavies** [comment]
This library does not (and has never) handled rendering: it only deals with positioning and sizing of words so that they don't overlap.  In fact, you can use SVG, canvas, or anything else to render the words once their positions and sizes have been computed.

I'm not sure what your issue is exactly, but it sounds like a problem with how you're using D3 and SVG for rendering.

(Aside: the use of the colour red internally is only for hidden extraction of glyphs, this doesn't affect whatever colours you use for rendering).

**Comment by alexresolute** [comment]
I guess I didn't really understand that based on the example. What is the point of providing a canvas if the library solely computes positioning of the given text? Not being snarky, I'm just trying to wrap my head around this.

**Comment by jasondavies** [comment]
You can provide an optional canvas generator for internal extraction of glyphs.  This is mainly for Node.js, where there is no DOM.

**Comment by alexresolute** [comment]
understood, thank you for the clarification
