### ISSUE TITLE
Instructions for installing from Bower

### ISSUE THREAD

**Issue by kedar2a** [jasondavies/d3-cloud#41]
Your work is awesome. And I am using **d3-cloud** in our project.

I can't find any instruction of installing it via **Bower** in *github-repo/demo page*.
It will be great to have it documented.

**Comment by jasondavies** [comment]
Does `bower install d3-cloud` work?  I’m not sure what the current requirements are: whether a `bower.json` is needed or not.

**Comment by cesine** [comment]
Hi @jasondavies 

* Yes `bower install d3-cloud` works, but this is because there are already 2 unofficial bower packages of your project.
* For us to use your codebase, you do need a `bower.json`


![screen shot 2015-06-23 at 9 08 25 am](https://cloud.githubusercontent.com/assets/196199/8306652/93649252-1987-11e5-826b-ef0f4fc26b59.png)
 
Can you reopen this, or accept one of the PRs so you can have a `bower.json`...
